### ISSUE TITLE
Upgrade Quickstart.UI to support IdentityServer 1.5.2

### ISSUE THREAD

**Issue by artstalker** [IdentityServer/IdentityServer4.Quickstart.UI#11]
I've just upgraded my IdentityServer to 1.5.2 and it  does not fit to this quickstart.ui code.

I have following static analysis error:
![image](https://user-images.githubusercontent.com/2846956/27084953-67971c82-5056-11e7-81ff-596195a80407.png)

**Comment by brockallen** [comment]
In general we label the QS to match what's released. Check the release branch for the latest. If you still have a problem, please reopen or comment here.
