### ISSUE TITLE
AccountController tossing errors...

### ISSUE THREAD

**Issue by innov83r** [IdentityServer/IdentityServer4.Quickstart.UI#12]
Trying to follow the QuickStart tutorials over at http://docs.identityserver.io/en/release/quickstarts and am working through http://docs.identityserver.io/en/release/quickstarts/3_interactive_login.html. I just ran 
`iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/IdentityServer/IdentityServer4.Quickstart.UI/release/get.ps1'))` 
and did not modify anything. When I build the solution I get the following:

![image](https://user-images.githubusercontent.com/1471588/27571423-a1cc5ee4-5ad3-11e7-8534-ba543a9d0eb7.png)

Is the issue the fact that I'm on .NET Core 1.0 and not 1.1?

**Comment by cdslijngard** [comment]
@innov83r Were you able to resolve the issue? I'm facing the same problem...

**Comment by innov83r** [comment]
Hey @cdslijngard, I did! Well I didn't, but someone on stackocerflow did for me: https://stackoverflow.com/q/44786475/1050275

Hth!

**Comment by cdslijngard** [comment]
@innov83r Hey thanks for the quick reply! I tried the fix, but it turns out I had to recreate the projects targeting .Net Core 1.1 instead of 1.0. Works now though, thanks!
