### ISSUE TITLE
README.md needs to be updated to aspnet core 2.0

### ISSUE THREAD

**Issue by arthur-rizzo** [IdentityServer/IdentityServer4.Quickstart.UI#19]
README.md page still refers to aspnet core 1.1. Since the project has been adapted to work with 2.0 readme should be updated as well.

**Comment by fekberg** [comment]
As a side not to this, please also include details for both ASP.NET Core 1.1 and ASP.NET Core 2.0 as it's confusing for users on ASP.NET Core 1.1 how to install this, without manually changing to the correct branch.

Referring specifically to this part: 
```
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/IdentityServer/IdentityServer4.Quickstart.UI/release/get.ps1'))
```

Would be extremely helpful if there was two headlines, one for ASP.NET Core 1.x and one for 2.x.

**Comment by leastprivilege** [comment]
should be fixed now.

**Comment by fekberg** [comment]
@leastprivilege No meaning in referring to v1 docs on the main readme?

**Comment by leastprivilege** [comment]
added
