### ISSUE TITLE
Using the master branch with asp.net core 2.0

### ISSUE THREAD

**Issue by SeanFarrow** [IdentityServer/IdentityServer4.Quickstart.UI#21]
Hi,

When using the master branch with asp.net core 2.0, I get the following build errors:
1>------ Build started: Project: Riskscoper.Identity.Provider, Configuration: Debug Any CPU ------
1>Quickstart\Account\AccountController.cs(118,67,118,80): error CS1503: Argument 3: cannot convert from 'string' to 'System.Security.Claims.ClaimsPrincipal'
1>Quickstart\Account\AccountController.cs(262,31,262,42): error CS1501: No overload for method 'SignInAsync' takes 5 arguments
1>Quickstart\Account\AccountService.cs(138,90,138,119): error CS1061: 'HttpContext' does not contain a definition for 'GetSchemeSupportsSignOutAsync' and no extension method 'GetSchemeSupportsSignOutAsync' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?)
1>Done building project "Riskscoper.Identity.Provider.csproj" -- FAILED.
Should I be using a different branch/do I need other packages (I've got Microsoft.aspnet.core 2.0 and Microsoft.aspnet.StaticFiles) installed.
Any help appreciated.
Cheers
Sean.

**Comment by bzuillsmith** [comment]
For the moment, it seems you can get quickstart files from the [IdentityServer4 repository itself](https://github.com/IdentityServer/IdentityServer4/tree/dev/src/Host). It's not quite as simple as copying and pasting a whole directory but with just a little work and experimentation, you can get it running.

**Comment by brockallen** [comment]
> When using the master branch with asp.net core 2.0

Use the dev branch or the label 2.0.0-rc1

**Comment by SeanFarrow** [comment]
Ok, I've copied all the files from the head of dav, I've got 3 errors, two of which I can fix, but the one that's giving me most trouble is:
1>Quickstart\Account\AccountService.cs(138,90,138,119): error CS1061: 'HttpContext' does not contain a definition for 'GetSchemeSupportsSignOutAsync' and no extension method 'GetSchemeSupportsSignOutAsync' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?)
Has this been deprecated/renamed?
How do I get access to the other label mentioned?
Cheers
Sean.

**Comment by brockallen** [comment]
>Quickstart\Account\AccountService.cs(138,90,138,119): error CS1061: 'HttpContext' does not contain a definition for 'GetSchemeSupportsSignOutAsync' and no extension method 

That's an extension method in IdSvr 2.0.0-rc1. It should be in scope.

**Comment by SeanFarrow** [comment]
Ok, it’s downloading 1.5, I’ll try updating to a prerelease.
Cheers
Sean.

**Comment by bzuillsmith** [comment]
@brockallen Thanks. 2.0.0-rc1 files worked for me

**Comment by SeanFarrow** [comment]
How do you get to that label/tag, which branch were you on?

**Comment by bzuillsmith** [comment]
Go to the "Code" tab of the repository and find a dropdown right under the tab that says "Branch: release". In that dropdown is a tab that says "Tags". click that and go to 2.0.0-rc1. You can download that whole repo version as a zip file and extract the 3 folders "Quickstart", "Views", "wwwroot" to your project.

[Here is a link](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/tree/2.0.0-rc1)

**Comment by SeanFarrow** [comment]
Ok, I've now got things building.
Can I just confirm that the AddTemporarySigningCertificate method has been replaced with AddDeveloperSigningCertificate as an extension method on IIdentityBuilder?

**Comment by brockallen** [comment]
@SeanFarrow yes, that's the new API for gen'ing a cert while testing. The rename was meant to make it more clear/explicit that you should not be using it in prod that way.

**Comment by SeanFarrow** [comment]
Yep, that is clear, I just wanted to check, is there a list of changes anywhere?

**Comment by brockallen** [comment]
There's an open docs issue under the main repo.

**Comment by SeanFarrow** [comment]
Ok, thanks, feel free to close this.
