### ISSUE TITLE
Problem with namespaces.

### ISSUE THREAD

**Issue by teamkiller7112** [IdentityServer/IdentityServer4.Quickstart.UI#22]
Hi, today i`am started to learn IdentityServer4.
I have some problems with Quickstart.UI:

1. Problem with SignInAsync.
![screenshot_9](https://user-images.githubusercontent.com/9117949/30070352-d3088e86-926b-11e7-9cf2-f3ba6834a280.png)

2. Problem with namespaces in AuthenticationProperties.
![screenshot_10](https://user-images.githubusercontent.com/9117949/30070407-f8796d70-926b-11e7-812e-7aea76b6e9ba.png)

I try to change namespace from IdentityServer4.Quickstart.UI to my Marvin.IDP.Quickstart.Account, but i have №1 problem.

ASP.NET Core 2.0
IdentityServer4 2.0.0-rc1
For downloading this UI i use PowerShell command from [adding-the-quickstart-ui](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI#adding-the-quickstart-ui)

Thanks for all answers =)

**Comment by leastprivilege** [comment]
You need to download the quickstart UI from the dev branch.

**Comment by teamkiller7112** [comment]
Thanks!
