### ISSUE TITLE
AngularJS - IdentityServer4.Quickstart.UI - 'AuthenticationProperties' is an ambiguous reference

### ISSUE THREAD

**Issue by fouadroumieh** [IdentityServer/IdentityServer4.Quickstart.UI#23]
I'm not sure if this issue been highlighted here, but am also getting the same issue, please check the details on this SO question:
https://stackoverflow.com/questions/46346042/angularjs-identityserver4-quickstart-ui-authenticationproperties-is-an-amb

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
