### ISSUE TITLE
`Microsoft.AspNetCore.All` depends from the required packages

### ISSUE THREAD

**Issue by gabrielweyer** [IdentityServer/IdentityServer4.Quickstart.UI#25]
There is no need to add:

- `Microsoft.AspNetCore.Mvc`
- `Microsoft.AspNetCore.StaticFiles`

As `Microsoft.AspNetCore.All` already depends on them:

![image](https://user-images.githubusercontent.com/2101647/31313242-0fe1f74e-ac29-11e7-8add-e190e931c855.png)

**Comment by leastprivilege** [comment]
see my comment on the PR
