### ISSUE TITLE
RazorPages Quickstart UI

### ISSUE THREAD

**Issue by martinfletcher** [IdentityServer/IdentityServer4.Quickstart.UI#27]
I am currently porting the Quickstart UI to RazorPages and would like to contribute this to the project.

As there will be conflicts within the project with both MVC and RazorPages (Layout page in Pages directory etc), what would be the best approach to getting this into the repo?

New Quickstart UI Repo for RazorPages?
New RazorPages Branch?
Move to RazorPages in dev?

Thanks

**Comment by leastprivilege** [comment]
Excuse my ignorance, but why?

**Comment by martinfletcher** [comment]
Its just another option.

I am migrating as the basis for conducting internal developer training and thought that it might be of use to the project.

**Comment by leastprivilege** [comment]
OK - no prob. If it's in our repo we must maintain it. We already have enough stuff to maintain ;)

Feel free to put your conversions into a repo you own - we will link to it.

**Comment by martinfletcher** [comment]
Ok no worries.

As per the contribution guides, is IdentityServer4.Quickstart.UI.RazorPages acceptable - or would you prefer it under *.IdentityServer4, or IdentityServer4.Contrib.*?

**Comment by leastprivilege** [comment]
why do you need a nuget package?

**Comment by martinfletcher** [comment]
Its for templates.

**Comment by leastprivilege** [comment]
I see - IdentityServer4.Contrib.*

**Comment by martinfletcher** [comment]
Ok no worries - Thanks.

I will let you know once complete, should be next day or two.

**Comment by leastprivilege** [comment]
thanks!

**Comment by grahamehorner** [comment]
@martinfletcher we would love to try out your #RazorPages implementation; we are currently using RazorPages to deliver an in house system as it has minimal need for controllers given the majority of the UI talks to a RESTful API services

**Comment by martinfletcher** [comment]
@grahamehorner Brilliant, you can track it here: https://github.com/IdentityServer4Contrib/IdentityServer4.Contrib.Templates.RazorPages

Currently getting it all together into this new public repo. It will contain the RazorPages implementation, and also some dotnet new templates.

I will update on this issue when complete/ready.

**Comment by brockallen** [comment]
I've added your repo link to our community docs: docs.identityserver.io/en/release/quickstarts/community.html#asp-net-core-mvc-razorpages-template-for-identityserver4-quickstart-ui
