### ISSUE TITLE
Question: Is there an example of Quickstart UI with changes for ASP.NET Identity and EF

### ISSUE THREAD

**Issue by dls314** [IdentityServer/IdentityServer4.Quickstart.UI#28]
IIRC there was an issue that linked to an example of the changes needed for ASP.NET Identity and EF support back around the IdentityServer4 v1 and ASP.NET v1 time frame.

Are there any similar examples using ASP.NET v2 and IdentityServer4 v2?

**Comment by brockallen** [comment]
There is now: https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage
