### ISSUE TITLE
Quickstart UI for an in-memory IdentityServer4, method name not updated

### ISSUE THREAD

**Issue by YaronSpawn** [IdentityServer/IdentityServer4.Quickstart.UI#3]
Hi
in the Quick start samples, the line "services.AddIdentityServerQuickstart" is not correct, 
need to update for AddDeveloperIdentityServer Or AddIdentityServer

see task 298 "Rename AddIdentityServerQuickstart to AddDeveloperIdentityServer" https://github.com/IdentityServer/IdentityServer4/issues/298 

Thanks in Advance, 
yaron hakon

**Comment by leastprivilege** [comment]
Where?

**Comment by YaronSpawn** [comment]
Here: https://github.com/IdentityServer/IdentityServer4.Quickstart.UI



Regards,



Yaron Hakon, Application Security Expert, AppSec Labs CEO

Mobile: +972-50-6668229 | Office: +972-52-3413555

Email: yaron@appsec-labs.com | Website: https://appsec-labs.com

[image: cid:image003.png@01D17AE4.10A2C550]





*From:* Dominick Baier [mailto:notifications@github.com]
*Sent:* Wednesday, October 19, 2016 11:32 AM
*To:* IdentityServer/IdentityServer4.Quickstart.UI <
IdentityServer4.Quickstart.UI@noreply.github.com>
*Cc:* YaronSpawn <yaron@appsec-labs.com>; Author <author@noreply.github.com>
*Subject:* Re: [IdentityServer/IdentityServer4.Quickstart.UI] Quickstart UI
for an in-memory IdentityServer4, method name not updated (#3)



Where?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/issues/3#issuecomment-254748729>,
or mute the thread

**Comment by leastprivilege** [comment]
thanks! You know that you can change the file yourself? ;)

**Comment by YaronSpawn** [comment]
I didn’t know, but for the next time …
