### ISSUE TITLE
ClaimPrincipal does not contain a definition for "GetDisplayName"

### ISSUE THREAD

**Issue by dulubi** [IdentityServer/IdentityServer4.Quickstart.UI#33]
Hi, 

In AccountController line 319 user.GetDisplayName() is giving the error:

"ClaimPrincipal does not contain a definition for 'GetDisplayName'..."

Should I just change it to user.GetName() or am I missing a reference here?

Thanks

**Comment by leastprivilege** [comment]
You need to update the IdentityServer4 package to latest.
