### ISSUE TITLE
Error from consent controller while building quickstart UI in identity server 4

### ISSUE THREAD

**Issue by mohamed-elsabagh** [IdentityServer/IdentityServer4.Quickstart.UI#4]
I am trying to add UI over my implementation of IdentityServer4, I am following the documentation quickstart guide https://identityserver4.readthedocs.io/en/release/quickstarts/3_interactive_login.html and I have copied folders from the release repo https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/tree/release When I try to build this solution on visual studio I get the following error:

Severity Code Description Project File Line Suppression State Error CS1061 'IResourceStore' does not contain a definition for 'FindEnabledResourcesByScopeAsync' and no extension method 'FindEnabledResourcesByScopeAsync' accepting a first argument of type 'IResourceStore' could be found (are you missing a using directive or an assembly reference?) TrialAuthentication..NETCoreApp,Version=v1.1 C:\Users\admin\trial-authentication\Controllers\ConsentController.cs 121 Active

**Comment by brockallen** [comment]
on rc5?

**Comment by mohamed-elsabagh** [comment]
"IdentityServer4": "1.0.0-rc5"

**Comment by RasmusRummel** [comment]
I had the exact same problem with IdentityServer4 1.0.0-rc4-update1. However the problem went away after updating to rc5.

**Comment by mohamed-elsabagh** [comment]
I tried to restore the packages again and working fine now, thanks so much it was my mistake
