### ISSUE TITLE
Another set of docs improvement suggestions

### ISSUE THREAD

**Issue by adriatic** [IdentityServer/IdentityServer4.Quickstart.UI#6]
This is a comment to the section with the header below:

### [Instructions](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/README.md#instructions)

> The assumption is that you started with an empty web application, added identityserver and configured the resources, clients and users.

_I would be great to provide a link to the best fitting sample from the **[Quickstarts](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts)** set as a more specific version of this sentence above. On the first glance - it is not clear how will this example, when created using the instructions in this tutorial be different from the sample described **[here](https://identityserver4.readthedocs.io/en/dev/quickstarts/6_aspnet_identity.html)**_

**Comment by leastprivilege** [comment]
PR

**Comment by brockallen** [comment]
PR the shit out of it

**Comment by adriatic** [comment]
Yes, I will - despite being very busy leading several relatively important open source projects dedicated to Aurelia. I genuinely care about IdentityServer and want to see it as successful as possible.

The reason for "peddling" suggestions is a simple optimization: i did not want to spend the time on something that might be irrelevant to you.
