### ISSUE TITLE
There are no examples of actually overriding any of the interfaces to provide Clients, Resources and Users

### ISSUE THREAD

**Issue by simps7b2** [IdentityServer/IdentityServer4.Quickstart.UI#9]
In every IdentityServer4 Quick Start sample there are in-memory providers given for the resources, clients, and users. But there aren't any samples of the proper interface overrides needed for production.

The documentation mentions some interfaces you need, but never shows you how to tie in those overrides. This problem is made worse by the fact that all the methods to override have a return type of Task. Also, there is no indication as to how to replace the IIdentityServer.AddTestUsers() call.

**Comment by leastprivilege** [comment]
Here's EF
https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html

..and ASP.NET Identity
https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html

what else are you looking for ?

**Comment by leastprivilege** [comment]
Feel free to write up your conclusions somewhere publicly so we can link to it and improve the docs.
